### ISSUE TITLE
iotnode.crt and iotnode.key missing ?

### ISSUE THREAD

**Issue by lakidd** [NZSmartie/IoTNode#3]
Hi
Trying to compile against the latest ESP-IDF I get 
``[lakidd1:...nteresting_projects/IoTNode]$ make all                                                                                                                                                                                         (master✱)
make[1]: *** No rule to make target `/Users/lakidd1/esp32/interesting_projects/IoTNode/main/iotnode.crt', needed by `embed_txt/iotnode.crt'.  Stop.
make: *** [main-build] Error 2``

and neither of those file are present.
If I touch iotnode.crt and iotnode.txt, it compiles fine (albeit with those files still empty)

**Comment by NZSmartie** [comment]
Heh, you beat me to it. I need to provide instructions on generating a certificate for use with DTLS. Although DTLS isn't used (commented out for now) you should be fine with blank files.
